### ISSUE TITLE
query selector is not a function error 

### ISSUE THREAD

**Issue by xalteropsx** [palerdot/vue-speedometer#66]
function Rt(t18) {
  return t18 == null ? Pt : function() {
    return this.querySelector(t18);
  };
}
vue-speedometer.es.js:312 Uncaught (in promise) TypeError: this.querySelector is not a function
    at Comment.<anonymous> (vue-speedometer.es.js:312:17)
    at Pe.select (vue-speedometer.es.js:603:34)
    at Proxy.renderGauge (vue-speedometer.es.js:3343:135)
    at Proxy.mounted (vue-speedometer.es.js:3321:8)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2685:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at flushJobs (runtime-core.esm-bundler.js:401:9)

**Comment by palerdot** [comment]
`runtimeCompiler` equivalent for Vite - https://github.com/vitejs/vite/discussions/4158

Adding this for future reference here so that people don't create new issues for their build setup issues.

**Comment by palerdot** [comment]
`v3` is published with composition api/SFC (single file component) support. This is the recommended version for `Vue 3` composition api users.
